### PR TITLE
Fix to issue #25

### PR DESCRIPTION
**Pull request by Therzok**
*Fixed trailing whitespaces/tabs and lines with just spaces/tabs.
*Changed whitespace to tab usage. Fixed indentation.
*Typo fix.
*Added missing </head> tag in a file.
*Compatibility fix for Python 3.0 print function.

### CODE REVIEW

**Comment by Therzok** [comment]
It looks scary, but it works. XD

**Comment by Therzok** [comment]
For some reason, it converted my tabs to 2spaces. o.O

Edit: Tested with a git clone on my fork again, and it seems to have applied tabs.

**Comment by dfilimon** [comment]
Wow, this diff is really crappy... :))

I'm just going to trust you here since I have 0 intentions of looking at thousands of lines of whitespace changes.

**Comment by Therzok** [comment]
Actual changes instead of indentation are here:
https://github.com/Therzok/Jeopy/commit/78453ec3754f1afedf1acbbffbbc471694470d9e#L13L143
https://github.com/Therzok/Jeopy/commit/e6d4e2b79c61f762d85c8f079bd0714516090e6e#L11R33
All the from __future__ import print_function additions.

**Pull request merged**
